### ISSUE TITLE
Workflow succeed while error in script occurs

### ISSUE THREAD

**Issue by donhardman** [manticoresoftware/publish_to_repo#2]
We need to address two problems in this task:

1. The action workflow does not fail, even when an error occurs during script execution upload. For instance, before we transitioned to using the find recursive search, there was an error when `build` dir was missing, and we didn't have `set -e` at all. 

2. The workflow should fail if there are no files in the directory and we have zero files to upload. Otherwise, we risk obscuring critical issues within our CI.

**Comment by KlimTodrik** [comment]
Done in [44d150d](https://github.com/manticoresoftware/publish_to_repo/commit/44d150d8fba6ccbe18e1d3c158ab6bcec94ea47d)
